### ISSUE TITLE
Not Working somehow, Please fix it, Thank you.

### ISSUE THREAD

**Issue by Johanna007** [v1shwa/gdget#2]
Hi Please Make the script to resume files. By the way the downloading not succeeding to 100%, Somehow it is not downloading successfully, Please fix it.

**Comment by v1shwa** [comment]
Could you please elaborate? I use it almost everyday & it works for me. Are you trying to download a folder? @johanna007

**Comment by v1shwa** [comment]
Closing this as the issue is not clear.
